import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';

function money(cents:number|null|undefined){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((cents??0)/100)}

export default async function Portal(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser();
 if(!user) return <main><section><div className="container"><div className="form"><h1>Customer portal</h1><p className="muted">Use a secure email link to view your rentals, balances, receipts, extensions and document status.</p><Link className="btn" href="/customer-login">Send Me a Secure Link</Link></div></div></section></main>;
 const {data:bookings}=await supabase.from('bookings').select('*,trailers(name)').eq('customer_id',user.id).order('pickup_at',{ascending:false});
 const bookingIds=(bookings??[]).map((b:any)=>b.id);
 const [{data:charges},{data:payments},{data:extensions}]=bookingIds.length?await Promise.all([
  supabase.from('charges').select('id,booking_id,type,description,amount_cents,status,stripe_invoice_id,paid_at,created_at').in('booking_id',bookingIds).order('created_at',{ascending:false}),
  supabase.from('payments').select('id,booking_id,amount_cents,status,stripe_receipt_url,paid_at').in('booking_id',bookingIds).order('paid_at',{ascending:false}),
  supabase.from('extensions').select('id,booking_id,requested_return_at,approved_return_at,amount_cents,status').in('booking_id',bookingIds).order('requested_return_at',{ascending:false}),
 ]):[{data:[]},{data:[]},{data:[]}];
 return <main><section><div className="container"><span className="eyebrow">Secure customer area</span><h1>Your rentals</h1>{!bookings?.length?<div className="panel"><p>No rentals are connected to {user.email} yet.</p><p className="muted">Make sure you signed in with the same email used on your booking request.</p></div>:<div className="grid">{bookings.map((b:any)=>{const rentalCharges=(charges??[]).filter((c:any)=>c.booking_id===b.id);const rentalPayments=(payments??[]).filter((p:any)=>p.booking_id===b.id);const rentalExtensions=(extensions??[]).filter((e:any)=>e.booking_id===b.id);const balance=Math.max((b.total_cents??0)-(b.amount_paid_cents??0),0)+rentalCharges.filter((c:any)=>c.status==='pending').reduce((sum:number,c:any)=>sum+c.amount_cents,0);return <article className="panel" key={b.id}><h2>{b.trailers?.name}</h2><p>Status: <strong style={{textTransform:'capitalize'}}>{b.status.replaceAll('_',' ')}</strong></p><p>{new Date(b.pickup_at).toLocaleString('en-US',{timeZone:'America/New_York'})} — {new Date(b.return_at).toLocaleString('en-US',{timeZone:'America/New_York'})}</p><p>Confirmation: <strong>{b.confirmation_code}</strong></p><div className="chips"><span className="chip">Total {money(b.total_cents)}</span><span className="chip">Paid {money(b.amount_paid_cents)}</span><span className="chip">Balance {money(balance)}</span></div><p className="muted">Documents: {b.drivers_license_path&&b.insurance_path?'On file':'Incomplete'}</p>{rentalExtensions.length>0&&<div><h3>Extensions</h3>{rentalExtensions.map((e:any)=><p key={e.id} className="muted">{e.status.replaceAll('_',' ')} · {money(e.amount_cents)} · return {new Date(e.approved_return_at||e.requested_return_at).toLocaleString('en-US',{timeZone:'America/New_York'})}</p>)}</div>}{rentalCharges.length>0&&<div><h3>Additional charges</h3>{rentalCharges.map((c:any)=><p key={c.id} className="muted">{c.description||c.type.replaceAll('_',' ')} · {money(c.amount_cents)} · {c.status}</p>)}</div>}{rentalPayments.some((p:any)=>p.stripe_receipt_url)&&<div className="actions">{rentalPayments.filter((p:any)=>p.stripe_receipt_url).map((p:any)=><a className="btn2" href={p.stripe_receipt_url} key={p.id} target="_blank" rel="noreferrer">View Receipt</a>)}</div>}</article>})}</div>}</div></section></main>
}
